library:
  source-dirs: src
tests:
  sandpiles-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandpiles
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- vector
- base >= 4.7 && < 5
- matrix
- JuicyPixels
- vector
- deepseq
- repa
name: sandpiles
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/sandpiles
license: BSD3
executables:
  sandpiles-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -funfolding-keeness-factor1000
    - -optlo-O3
    - -with-rtsopts=-N
    dependencies:
    - sandpiles
description: Please see the README on GitHub at <https://github.com/githubuser/sandpiles#readme>
